# Generated by Django 3.1.7 on 2021-04-19 16:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Devision',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('devision', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.ImageField(default='default.jpg', null=True, upload_to='profile_pic')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Customer Profile',
            },
        ),
        migrations.CreateModel(
            name='Deliverycharges',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery_charge', models.IntegerField(blank=True, default=0, null=True)),
                ('division_in_charge', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.devision')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Delivery Charge',
            },
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(help_text='Please Enter Your Valid Phone Number.', max_length=128, null=True, region=None)),
                ('first_name', models.CharField(max_length=30, null=True)),
                ('last_name', models.CharField(max_length=30, null=True)),
                ('house_number', models.CharField(help_text='Your Village Name And House Number', max_length=32, null=True)),
                ('effective_delivery', models.CharField(choices=[('Home', 'Home'), ('Office', 'Office')], default='Home', max_length=30, null=True)),
                ('city', models.CharField(max_length=30, null=True)),
                ('zone', models.CharField(blank=True, max_length=30, null=True)),
                ('deliverycharges', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.deliverycharges')),
                ('devision', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.devision')),
                ('users', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Customer Address',
                'db_table': 'address',
            },
        ),
    ]
