# Generated by Django 3.1.7 on 2021-04-06 08:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='deliverycharges',
            options={'verbose_name_plural': 'Delivery Charge'},
        ),
    ]
