# Generated by Django 3.1.7 on 2021-04-07 15:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20210406_1402'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='devision',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='users.devision'),
            preserve_default=False,
        ),
    ]
