# Generated by Django 3.1.7 on 2021-04-09 11:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BannerImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banner_title', models.CharField(default='Banner Image', max_length=60)),
                ('banner_image', models.ImageField(help_text='image height should be 240px or 300px', upload_to='banner_image')),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titel', models.CharField(default='Contact', max_length=30)),
                ('shop_address', models.CharField(max_length=150)),
                ('facebook', models.CharField(help_text='Place Your Facebook Account Url', max_length=150)),
                ('twitter', models.CharField(help_text='Place Your twitter Account Url', max_length=150)),
                ('email', models.CharField(help_text='Place Your Email', max_length=150)),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(help_text='Please Enter Your Valid Phone Number.', max_length=128, region=None)),
            ],
        ),
        migrations.CreateModel(
            name='HeaderImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titel', models.CharField(help_text='This titel will appear in the Image', max_length=150)),
                ('header_image', models.ImageField(upload_to='header_image')),
            ],
        ),
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blog_title', models.CharField(max_length=60)),
                ('blog_description', models.TextField()),
                ('blog_image', models.ImageField(upload_to='blog_image')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('users', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
