# Generated by Django 3.1.7 on 2021-04-07 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bannerimage',
            name='banner_image_1',
        ),
        migrations.RemoveField(
            model_name='bannerimage',
            name='banner_image_2',
        ),
        migrations.AlterField(
            model_name='bannerimage',
            name='banner_image',
            field=models.ImageField(help_text='image height should be 240px or 300px', upload_to='banner_image'),
        ),
        migrations.AlterField(
            model_name='bannerimage',
            name='banner_title',
            field=models.CharField(default='Banner Image', max_length=60),
        ),
    ]
