# Generated by Django 3.1.7 on 2021-04-07 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20210407_2136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='titel',
            field=models.CharField(default='Contact', max_length=30),
        ),
        migrations.AlterField(
            model_name='headerimage',
            name='header_image',
            field=models.ImageField(upload_to='header_image'),
        ),
    ]
