# Generated by Django 3.1.7 on 2021-04-08 08:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StripePaymentStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stripe_charge_id', models.CharField(blank=True, max_length=400, null=True)),
                ('create_date', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Stripe Payment Statement',
            },
        ),
        migrations.CreateModel(
            name='CashOnDeliveryPaymentStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Payment_statement', models.CharField(blank=True, default='Cash on delivery', max_length=100, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Cash On Delivery Payment Statement',
            },
        ),
        migrations.CreateModel(
            name='BkashPaymentStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transation_status', models.CharField(blank=True, max_length=50, null=True)),
                ('paymentId', models.CharField(max_length=50, null=True)),
                ('trxId', models.CharField(max_length=50, null=True)),
                ('merchant_invoice_number', models.CharField(max_length=80, null=True)),
                ('amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=11, null=True)),
                ('currency', models.CharField(default='BDT', max_length=50, null=True)),
                ('intent', models.CharField(max_length=50, null=True)),
                ('create_time', models.CharField(blank=True, max_length=100, null=True)),
                ('update_time', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Bkash Payment Status',
            },
        ),
    ]
