# Generated by Django 3.1.7 on 2021-04-06 03:38

from django.db import migrations, models
import shortuuid.main


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordered', models.BooleanField(default=False)),
                ('quantity', models.IntegerField(default=1, null=True)),
                ('cart_id', models.CharField(blank=True, default=shortuuid.main.ShortUUID.uuid, max_length=250, null=True, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Customer Shopping Cart Item',
            },
        ),
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=15)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subtotal', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=50, null=True)),
                ('ordered_date', models.DateTimeField()),
                ('ref_code', models.CharField(blank=True, max_length=20, null=True)),
                ('start_date', models.DateTimeField(auto_now_add=True)),
                ('shoes_size', models.CharField(blank=True, max_length=255, null=True)),
                ('shirt_size', models.CharField(blank=True, max_length=255, null=True)),
                ('pant_size', models.CharField(blank=True, max_length=255, null=True)),
                ('ordered', models.BooleanField(default=False)),
                ('being_delivered', models.BooleanField(default=False)),
                ('is_order_cancel', models.BooleanField(default=False)),
                ('received', models.BooleanField(default=False)),
                ('refund_requested', models.BooleanField(default=False)),
                ('refund_granted', models.BooleanField(default=False)),
                ('order_number', models.CharField(blank=True, default=1054835212, editable=False, max_length=250, null=True, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Customer Order',
            },
        ),
        migrations.CreateModel(
            name='OrderCancel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField(blank=True, choices=[('CHANGE MY MIND', 'CHANGE MY MIND'), ('OTHER REASON', 'OTHER REASON')], default='CHANGE MY MIND', null=True)),
                ('accepted', models.BooleanField(default=False)),
                ('email', models.EmailField(max_length=254)),
            ],
            options={
                'verbose_name_plural': 'Order Cancel By Customer',
            },
        ),
        migrations.CreateModel(
            name='WishList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordered', models.BooleanField(default=False)),
                ('is_product_available', models.BooleanField(default=False)),
                ('wishlist_id', models.CharField(blank=True, max_length=250, null=True)),
            ],
        ),
    ]
