# Generated by Django 3.1.7 on 2021-04-06 03:53

from django.db import migrations, models
import random
import shortuuid.main


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_auto_20210406_0938'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='cart_id',
            field=models.CharField(blank=True, default=shortuuid.main.ShortUUID.uuid, max_length=250, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_number',
            field=models.CharField(blank=True, default=random.Random.randint, editable=False, max_length=250, null=True, unique=True),
        ),
    ]
