# Generated by Django 3.1.7 on 2021-04-06 06:04

from django.db import migrations, models
import shortuuid.main


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0004_auto_20210406_0955'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='cart_id',
            field=models.CharField(blank=True, default=shortuuid.main.ShortUUID.uuid, max_length=250, null=True, unique=True),
        ),
    ]
