# Generated by Django 3.1.7 on 2021-04-06 08:02

from django.db import migrations, models
import shortuuid.main


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0005_auto_20210406_1204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='cart_id',
            field=models.CharField(blank=True, default=shortuuid.main.ShortUUID.uuid, max_length=250, null=True, unique=True),
        ),
    ]
